default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: andre
  password: 123
  timeout: 5000

development:
  <<: *default
  database: CAMAAR_development

test:
  <<: *default
  database: CAMAAR_test

production:
  <<: *default
  database: CAMAAR_production
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
